name: sonarcloud_terraform_provider

on:
  push:
    branches: 
      - main

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Build:
    runs-on: ubuntu-latest
    name: sonarcloud_terraform_provider
    steps:
      - name: import GPG key
        id: import_gpg
        uses: paultyng/ghaction-import-gpg@v2.1.0
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: install go binary
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15.5
      - name: code checkout
        uses: actions/checkout@v2
      - name: generate semantic version
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
      - name: print semantic version
        id: tag_maker
        run: |
          new_version=${{ steps.tag_version.outputs.new_version }}
          new_tag=${{ steps.tag_version.outputs.new_tag }}
          echo "::set-output name=new_tag::${new_tag}"
          echo "::set-output name=new_version::${new_version}"
      - name: linting go code
        uses: Jerome1337/golint-action@v1.0.2
      - name: build sonarcloud terraform provider
        run: |
          make build
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      new_version: ${{ steps.tag_version.outputs.new_version }}    
